---
# https://circleci.com/docs/docker
version: 2
jobs:
  build:
    docker:
      # https://github.com/jumanjihouse/cci/pulls?q=is%3Apr+is%3Aclosed
      - image: jumanjiman/cci:20180408T1654-git-5806ceb

    working_directory: ~/workdir/

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Build the image
          command: |
            ci/build.sh

      - run:
          name: Show licenses
          command: |
            ci/licenses.sh

      - run:
          name: Test the image
          command: |
            ci/test.sh

      - deploy:
          name: Deploy from master branch
          # yamllint disable rule:line-length
          command: |
            if [[ ${CIRCLE_BRANCH} = master ]] && [[ -z ${CIRCLE_PR_NUMBER} ]]; then
              ci/publish.sh
            fi
